package com.se310.store.observer;

import java.util.HashMap;
import java.util.Map;

/**
 * Observer implementation that collects statistics about
 * events and commands generated by devices.
 *
 * This observer maintains two maps: one for event counts and
 * another for command counts. Each time an observable device
 * notifies observers, DeviceStatistics increments the relevant
 * counter and prints a running total for that device.
 *
 * @author  Sergey L. Sundukovskiy
 * @version 1.0
 * @since   2025-09-25
 */
public class DeviceStatistics implements Observer {

    //TODO: Implement Observer interface
    //TODO: Track event and command counts per device

    private final Map<String, Integer> eventCounts;
    private final Map<String, Integer> commandCounts;

    /**
     * Default constructor initializes empty count maps.
     */
    public DeviceStatistics() {
        this.eventCounts = new HashMap<>();
        this.commandCounts = new HashMap<>();
    }

    /**
     * Receives updates from devices and updates the statistics.
     *
     * @param deviceId  the unique ID of the device sending the update
     * @param eventType the type of event or command
     * @param message   the message describing the update
     */
    @Override
    public void update(String deviceId, String eventType, String message) {
        if (deviceId==null|| eventType==null){
            return;
        }
        String type = eventType.toLowerCase();
        if (type.contains("event")){
            eventCounts.merge(deviceId, 1, Integer::sum);
        }
        else if (type.contains("command")){
            commandCounts.merge(deviceId, 1, Integer::sum);
        }
        System.out.println("Device: " + deviceId);
        System.out.println("Event count: " + eventCounts.getOrDefault(deviceId, 0));
        System.out.println("Command count: " + commandCounts.getOrDefault(deviceId, 0));
    }
}